# Generated by Django 4.0.3 on 2022-03-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projects',
            new_name='user',
        ),
    ]
