# Generated by Django 4.0.3 on 2022-03-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='project-images/'),
        ),
    ]
